name: CI

on:
  push:
    branches: [ main ]
    tags-ignore: ['v*']
  pull_request:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    if: |
      github.event_name != 'push' ||
      !startsWith(github.event.head_commit.message, 'chore: bump version')

    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt -- --check

      # Let's back off this until we have time to address it.
      # - name: Run clippy
      #   run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --verbose

      - name: Build
        run: cargo build --release --verbose

  autotag:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/auto-tag.yml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  release:
    needs: autotag
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.autotag.outputs.new_tag }}
